const API_BASE = (import.meta.env.VITE_API_BASE_URL || '/api/v1').replace(/\/$/, '');

async function request(path, options = {}) {
  const response = await fetch(`${API_BASE}${path}`, options);
  const text = await response.text();
  let payload = {};
  try { payload = text ? JSON.parse(text) : {}; } catch { payload = { detail: text }; }
  if (!response.ok) throw new Error(typeof payload.detail === 'string' ? payload.detail : `Request failed (${response.status})`);
  return payload;
}

function mapAssessment(a) {
  return {
    riskScore: a.overall_risk_score,
    riskLevel: a.risk_level === 'CRITICAL' ? 'HIGH' : a.risk_level,
    anomalies: (a.explainable_flags || []).map((title, i) => ({
      id: `${a.project_id}-AI-${i + 1}`,
      type: title.toLowerCase().includes('image') ? 'DUPLICATE_IMAGE' : title.toLowerCase().includes('vendor') ? 'VENDOR_CARTEL' : title.toLowerCase().includes('timeline') || title.toLowerCase().includes('overrun') ? 'TIMELINE_DELAY' : 'COST_ANOMALY',
      title, severity: a.risk_level, confidence: Math.round(Math.max(50, a.overall_risk_score)),
      description: title, evidence: 'Generated by the MPLADS-AI risk engine.'
    })),
    overrunProbability: a.overrun_probability, mlAnomalyScore: a.ml_anomaly_score
  };
}

function mapProject(p, assessment) {
  const a = mapAssessment(assessment);
  return {
    id:p.project_id,name:p.title,category:p.category,location:`${p.district}, ${p.state}`,district:p.district,state:p.state,mpName:p.constituency,
    implementingAgency:'MPLADS Implementing Agency',contractor:p.contractor_name,sanctionedAmount:p.sanctioned_amount,releasedAmount:p.funds_released,utilizedAmount:p.funds_utilized,
    remainingAmount:Math.max(0,p.sanctioned_amount-p.funds_utilized),sanctionDate:p.sanction_date,startDate:p.sanction_date,targetDate:p.expected_completion_date,
    currentStage:p.physical_progress_pct>=100?'Completed':'Work Progress',progressPercent:p.physical_progress_pct,status:p.status||(a.riskScore>=60?'FLAGGED':'MONITORED'),
    riskScore:a.riskScore,riskLevel:a.riskLevel,coordinates:[p.latitude,p.longitude],lastUpdated:new Date().toISOString(),
    slaDaysLeft:p.allocated_duration_days-p.days_elapsed,slaUrgency:(p.allocated_duration_days-p.days_elapsed)<0?'CRITICAL':'SAFE',images:{uploaded:p.evidence_image_url || undefined},anomalies:a.anomalies,backendRecord:p,assessment
  };
}
async function getRawProjects(filters={}) {
  const qs=new URLSearchParams();
  if(filters.state&&filters.state!=='ALL') qs.set('state',filters.state);
  if(filters.district&&filters.district!=='ALL') qs.set('district',filters.district);
  if(filters.search) qs.set('search',filters.search);
  const records=await request(`/analytics/projects${qs.toString()?`?${qs}`:''}`);
  const assessments=await Promise.all(records.map(p=>request(`/analytics/score-project/${encodeURIComponent(p.project_id)}`)));
  return records.map((p,i)=>mapProject(p,assessments[i]));
}
export const api={
  getNationalKPIs:async()=>{const p=await getRawProjects();const f=p.reduce((s,x)=>s+x.sanctionedAmount,0);return{success:true,data:{totalProjects:p.length,totalFundsCr:(f/1e7).toFixed(2),projectsMonitored:p.length,anomaliesDetected:p.reduce((s,x)=>s+x.anomalies.length,0),highRiskProjects:p.filter(x=>x.riskScore>=60).length,slaAtRisk:p.filter(x=>x.slaDaysLeft<14).length,trends:{totalProjects:'Live',totalFundsCr:'Live',anomaliesDetected:'Live',highRiskProjects:'Live',slaAtRisk:'Live'}}};},
  getStateRiskData:async()=>{const p=await getRawProjects(),g={};for(const x of p){g[x.state]??={state:x.state,totalProjects:0,anomalies:0,highRisk:0,delayed:0,center:x.coordinates};g[x.state].totalProjects++;g[x.state].anomalies+=x.anomalies.length;g[x.state].highRisk+=x.riskScore>=60?1:0;g[x.state].delayed+=x.slaDaysLeft<0?1:0;}return{success:true,data:Object.values(g).map(x=>({...x,fraudRiskPct:x.totalProjects?Math.round(x.highRisk/x.totalProjects*100):0,riskLevel:x.highRisk?'HIGH':'LOW',code:x.state.slice(0,2).toUpperCase()}))};},
  getMonthlyTrends:async()=>{const p=await getRawProjects();return{success:true,data:[{month:'Live portfolio',cost:p.filter(x=>x.anomalies.some(a=>a.type==='COST_ANOMALY')).length,duplicateImage:p.filter(x=>x.anomalies.some(a=>a.type==='DUPLICATE_IMAGE')).length,vendorCartel:p.filter(x=>x.anomalies.some(a=>a.type==='VENDOR_CARTEL')).length,delayed:p.filter(x=>x.slaDaysLeft<0).length,total:p.reduce((s,x)=>s+x.anomalies.length,0)}]};},
  getFraudBreakdown:async()=>{const p=await getRawProjects();return{success:true,data:[['Cost / Financial Anomalies','COST_ANOMALY'],['Duplicate Evidence','DUPLICATE_IMAGE'],['Vendor Concentration','VENDOR_CARTEL'],['Timeline / Overrun Risk','TIMELINE_DELAY']].map(([name,type])=>({name,value:p.filter(x=>x.anomalies.some(a=>a.type===type)).length}))};},
  getProjects:async(f={})=>{let d=await getRawProjects(f);if(f.riskLevel&&f.riskLevel!=='ALL')d=d.filter(p=>p.riskLevel===f.riskLevel);if(f.status&&f.status!=='ALL')d=d.filter(p=>p.status===f.status);return{success:true,data:d,total:d.length};},
  getProjectById:async(id)=>{const r=await request('/analytics/projects'),p=r.find(x=>x.project_id.toLowerCase()===id.toLowerCase());if(!p)return{success:false,error:'Project not found'};const a=await request(`/analytics/score-project/${encodeURIComponent(p.project_id)}`);return{success:true,data:mapProject(p,a)};},
  getHighRiskProjects:async()=>{const r=await api.getProjects(),d=r.data.filter(p=>p.riskScore>=60);return{success:true,data:d,total:d.length};},
  updateProjectDecision:async(id,decision,remarks='')=>{await request(`/analytics/projects/${encodeURIComponent(id)}/decision?${new URLSearchParams({decision,remarks})}`,{method:'POST'});return api.getProjectById(id);},
  getCartelNetwork:async(district='Varanasi')=>({success:true,data:await request(`/cartel/matrix?district=${encodeURIComponent(district)}`)}),
  getSLAAlerts:async()=>{const p=await getRawProjects();return{success:true,data:p.filter(x=>x.slaDaysLeft<14).map(x=>({id:`SLA-${x.id}`,projectId:x.id,district:x.district,state:x.state,projectName:x.name,risk:x.riskScore>=60?'CRITICAL':'MEDIUM',daysLeft:x.slaDaysLeft}))};},
  getCitizenReports:async()=>request('/operations/reports'),
  submitCitizenReport:async d=>request('/operations/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}),
  getNotifications:async()=>request('/operations/notifications'),
  markNotificationRead:async id=>request(`/operations/notifications/${encodeURIComponent(id)}/read`,{method:'POST'})
};
