export const NATIONAL_KPIS = {
  totalProjects: 12482,
  totalFundsCr: 2486.5,
  projectsMonitored: 11920,
  anomaliesDetected: 183,
  highRiskProjects: 42,
  slaAtRisk: 96,
  trends: {
    totalProjects: '+8.4% vs last FY',
    totalFundsCr: '+12.1% vs last FY',
    projectsMonitored: '95.5% coverage',
    anomaliesDetected: '-14.2% (early caught)',
    highRiskProjects: '+5 new this week',
    slaAtRisk: '12 urgent <48h',
  }
};

export const MOCK_PROJECTS = [
  {
    id: 'MPLAD-2026-00124',
    name: 'Rural Road Construction & Paver Block Laying',
    category: 'Roads & Infrastructure',
    location: 'Chiraigaon Block, XYZ Village',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    mpName: 'Shri Narendra Modi (Varanasi PC)',
    implementingAgency: 'Rural Engineering Services (RES), Div-2',
    contractor: 'Apex Infra & BuildTech Pvt Ltd',
    sanctionedAmount: 4800000,
    releasedAmount: 3200000,
    utilizedAmount: 2100000,
    remainingAmount: 2700000,
    sanctionDate: '2025-08-15',
    startDate: '2025-10-01',
    targetDate: '2026-03-31',
    currentStage: 'Work Progress',
    progressPercent: 45,
    status: 'UNDER_INVESTIGATION',
    riskScore: 87,
    riskLevel: 'HIGH',
    coordinates: [25.3176, 82.9739],
    lastUpdated: '2026-08-21T14:30:00Z',
    slaDaysLeft: 4,
    slaUrgency: 'HIGH',
    images: {
      uploaded: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%2Fid%2FOIP.3dm7d3iD_CNAtTQMp22DUQHaEu%3Fr%3D0%26pid%3DApi&f=1&ipt=08e3923244a23d76cd19ec9fff62db7b1fc3c11e2572fd1aa59a7624b944bb79&ipo=images',
      matched: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%2Fid%2FOIP.3dm7d3iD_CNAtTQMp22DUQHaEu%3Fr%3D0%26pid%3DApi&f=1&ipt=08e3923244a23d76cd19ec9fff62db7b1fc3c11e2572fd1aa59a7624b944bb79&ipo=images',
      uploadedMeta: {
        timestamp: '2026-08-20 16:42 IST',
        device: 'Realme 9 Pro (5G)',
        gps: '25.3190° N, 82.9810° E',
        geotagStatus: 'MATCH_PROXIMITY_OK',
        fileSize: '4.2 MB',
      },
      matchedMeta: {
        sourceProjectId: 'MPLAD-2024-00892',
        sourceProjectName: 'Gram Panchayat Road, Jaunpur',
        sourceDate: '2024-11-12',
        matchType: 'Perceptual Hash Exact Match',
        similarityPercent: 96,
      }
    },
    anomalies: [
      {
        id: 'ANO-101',
        type: 'COST_ANOMALY',
        title: 'Cost Anomaly Detected',
        severity: 'HIGH',
        confidence: 94,
        description: 'Sanctioned rate of ₹1,600/sq.m is 42% higher than District Schedule of Rates (DSR baseline ₹1,120/sq.m).',
        evidence: 'DSR 2025-26 benchmark comparison, RES Div-2 average variance.',
      },
      {
        id: 'ANO-102',
        type: 'DUPLICATE_IMAGE',
        title: 'Duplicate Evidence Image Match (96%)',
        severity: 'CRITICAL',
        confidence: 96,
        description: 'Physical progress photo submitted matches previous completed project in Jaunpur (MPLAD-2024-00892).',
        evidence: 'Convolutional neural feature distance: 0.04 (96% pixel & texture alignment).',
      },
      {
        id: 'ANO-103',
        type: 'VENDOR_CARTEL',
        title: 'Vendor Collusion & Cross-Bidding Pattern',
        severity: 'HIGH',
        confidence: 89,
        description: 'Vendor "Apex Infra" shares registered GST director and bank branch with 2 rival bidder firms in tender.',
        evidence: 'ROC filings graph, common GSTIN mobile hash, IP address submission overlap.',
      },
      {
        id: 'ANO-104',
        type: 'TIMELINE_DELAY',
        title: 'Milestone Discrepancy & Fund Release Lag',
        severity: 'MEDIUM',
        confidence: 82,
        description: 'Second installment released 60 days before field MB (Measurement Book) recording.',
        evidence: 'PFMS transaction log vs RES field inspection log mismatch.',
      }
    ],
    timeline: [
      { stage: 'Approved & Sanctioned', date: '15 Aug 2025', status: 'completed' },
      { stage: '1st Installment Released (₹32L)', date: '10 Oct 2025', status: 'completed' },
      { stage: 'Earthwork & Base Layer', date: '28 Nov 2025', status: 'completed' },
      { stage: 'Paving & Surfacing', date: '18 Jan 2026', status: 'in-progress' },
      { stage: 'District Inspection', date: 'Pending', status: 'pending' },
      { stage: 'Completion Certificate', date: 'Pending', status: 'pending' },
    ]
  },
  {
    id: 'MPLAD-2026-00231',
    name: 'Multi-purpose Community Hall Construction',
    images: { uploaded: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80' },
    category: 'Community Assets',
    location: 'Sector 4, Rohini',
    district: 'North West Delhi',
    state: 'Delhi',
    mpName: 'Dr. Harsh Vardhan (Chandni Chowk)',
    implementingAgency: 'Delhi Development Authority (DDA)',
    contractor: 'Vanguard Civilcon LLP',
    sanctionedAmount: 3200000,
    releasedAmount: 2800000,
    utilizedAmount: 1400000,
    remainingAmount: 1800000,
    sanctionDate: '2025-06-10',
    startDate: '2025-07-15',
    targetDate: '2026-02-28',
    currentStage: 'Work Progress',
    progressPercent: 35,
    status: 'FLAGGED',
    riskScore: 78,
    riskLevel: 'HIGH',
    coordinates: [28.7041, 77.1025],
    lastUpdated: '2026-08-22T09:15:00Z',
    slaDaysLeft: 2,
    slaUrgency: 'CRITICAL',
    anomalies: [
      {
        id: 'ANO-105',
        type: 'UNDER_UTILIZED',
        title: 'Disbursed Funds Idle for >120 Days',
        severity: 'HIGH',
        confidence: 91,
        description: '₹14L installment lying unspent in escrow account without structural progress.',
        evidence: 'DDA Escrow Statement vs Physical Progress Audit',
      }
    ]
  },
  {
    id: 'MPLAD-2026-00451',
    name: 'Solar Drinking Water RO Plant & Borewell',
    images: { uploaded: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80' },
    category: 'Drinking Water & Sanitation',
    location: 'Banswara Tribal Block',
    district: 'Banswara',
    state: 'Rajasthan',
    mpName: 'Shri Kanakmal Katara',
    implementingAgency: 'Public Health Engineering Dept (PHED)',
    contractor: 'SunPower Aqua Solutions',
    sanctionedAmount: 5100000,
    releasedAmount: 4500000,
    utilizedAmount: 4100000,
    remainingAmount: 1000000,
    sanctionDate: '2025-04-12',
    startDate: '2025-05-20',
    targetDate: '2025-12-31',
    currentStage: 'Inspection',
    progressPercent: 88,
    status: 'UNDER_INVESTIGATION',
    riskScore: 95,
    riskLevel: 'CRITICAL',
    coordinates: [23.5461, 74.4373],
    lastUpdated: '2026-08-23T11:00:00Z',
    slaDaysLeft: -45,
    slaUrgency: 'CRITICAL',
    anomalies: [
      {
        id: 'ANO-106',
        type: 'GEO_MISMATCH',
        title: 'Geotagged Asset Outside Constituency',
        severity: 'CRITICAL',
        confidence: 98,
        description: 'Uploaded commissioning photo GPS points 34km across the Madhya Pradesh border (Ratlam District).',
        evidence: 'Geo-fencing boundary breach; EXIF Coordinate extraction.',
      }
    ]
  },
  {
    id: 'MPLAD-2026-00089',
    name: 'Digital Smart Classroom Lab & Computer Setup',
    images: { uploaded: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop&q=80' },
    category: 'Education & Skill Development',
    location: 'Govt Model Higher Secondary School',
    district: 'Patna',
    state: 'Bihar',
    mpName: 'Shri Ravi Shankar Prasad',
    implementingAgency: 'Bihar State Educational Infra Corp',
    contractor: 'EdTech Next India Ltd',
    sanctionedAmount: 1800000,
    releasedAmount: 1800000,
    utilizedAmount: 1750000,
    remainingAmount: 50000,
    sanctionDate: '2025-09-01',
    startDate: '2025-10-15',
    targetDate: '2026-01-30',
    currentStage: 'Completed',
    progressPercent: 100,
    status: 'VERIFIED',
    riskScore: 12,
    riskLevel: 'LOW',
    coordinates: [25.5941, 85.1376],
    lastUpdated: '2026-08-19T10:20:00Z',
    slaDaysLeft: 30,
    slaUrgency: 'SAFE',
    anomalies: []
  },
  {
    id: 'MPLAD-2026-00342',
    name: 'Primary Health Centre (PHC) Medical Oxygen Pipeline',
    images: { uploaded: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80' },
    category: 'Public Health',
    location: 'Baramati Rural Hospital',
    district: 'Pune',
    state: 'Maharashtra',
    mpName: 'Smt. Supriya Sule',
    implementingAgency: 'Public Works Department (PWD Pune)',
    contractor: 'Lifecare Gas Grid Corp',
    sanctionedAmount: 6400000,
    releasedAmount: 5000000,
    utilizedAmount: 4800000,
    remainingAmount: 1600000,
    sanctionDate: '2025-03-15',
    startDate: '2025-04-10',
    targetDate: '2025-10-30',
    currentStage: 'Completed',
    progressPercent: 100,
    status: 'COMPLETED',
    riskScore: 24,
    riskLevel: 'LOW',
    coordinates: [18.5204, 73.8567],
    lastUpdated: '2026-08-15T16:00:00Z',
    slaDaysLeft: 60,
    slaUrgency: 'SAFE',
    anomalies: []
  },
  {
    id: 'MPLAD-2026-00518',
    name: 'High-Mast LED Street Lighting (50 Junctions)',
    category: 'Energy & Lighting',
    location: 'Guwahati Metropolitan Area',
    district: 'Kamrup Metro',
    state: 'Assam',
    mpName: 'Smt. Queen Oja',
    implementingAgency: 'Guwahati Smart City Dev Corp',
    contractor: 'Apex Infra & BuildTech Pvt Ltd',
    sanctionedAmount: 2900000,
    releasedAmount: 2900000,
    utilizedAmount: 1200000,
    remainingAmount: 1700000,
    sanctionDate: '2025-07-22',
    startDate: '2025-09-01',
    targetDate: '2026-04-30',
    currentStage: 'Work Progress',
    progressPercent: 40,
    status: 'FLAGGED',
    riskScore: 74,
    riskLevel: 'HIGH',
    coordinates: [26.1445, 91.7362],
    lastUpdated: '2026-08-20T12:00:00Z',
    slaDaysLeft: 8,
    slaUrgency: 'MEDIUM',
    anomalies: [
      {
        id: 'ANO-107',
        type: 'VENDOR_CARTEL',
        title: 'Common Contractor Overlap in High Risk Pool',
        severity: 'HIGH',
        confidence: 88,
        description: 'Contractor is currently under investigation in UP for duplicate photo submissions.',
        evidence: 'Centralized Pan-India Vendor Tracking Flag.',
      }
    ]
  }
];

export const STATE_RISK_DATA = [
  { state: 'Uttar Pradesh', code: 'UP', totalProjects: 1840, anomalies: 41, highRisk: 12, fraudRiskPct: 24, delayed: 32, center: [26.8467, 80.9462], riskLevel: 'HIGH' },
  { state: 'Bihar', code: 'BR', totalProjects: 1210, anomalies: 34, highRisk: 9, fraudRiskPct: 28, delayed: 28, center: [25.0961, 85.3131], riskLevel: 'HIGH' },
  { state: 'Maharashtra', code: 'MH', totalProjects: 1420, anomalies: 18, highRisk: 4, fraudRiskPct: 12, delayed: 14, center: [19.7515, 75.7139], riskLevel: 'LOW' },
  { state: 'Rajasthan', code: 'RJ', totalProjects: 980, anomalies: 27, highRisk: 8, fraudRiskPct: 22, delayed: 19, center: [27.0238, 74.2179], riskLevel: 'CRITICAL' },
  { state: 'Delhi (UT)', code: 'DL', totalProjects: 410, anomalies: 12, highRisk: 3, fraudRiskPct: 15, delayed: 8, center: [28.7041, 77.1025], riskLevel: 'MEDIUM' },
  { state: 'Assam', code: 'AS', totalProjects: 560, anomalies: 16, highRisk: 4, fraudRiskPct: 18, delayed: 11, center: [26.2006, 92.9376], riskLevel: 'MEDIUM' },
  { state: 'Karnataka', code: 'KA', totalProjects: 1120, anomalies: 14, highRisk: 2, fraudRiskPct: 9, delayed: 9, center: [15.3173, 75.7139], riskLevel: 'LOW' },
  { state: 'West Bengal', code: 'WB', totalProjects: 990, anomalies: 21, highRisk: 5, fraudRiskPct: 19, delayed: 17, center: [22.9868, 87.8550], riskLevel: 'MEDIUM' },
];

export const MONTHLY_ANOMALY_TRENDS = [
  { month: 'Mar 25', cost: 18, duplicateImage: 8, vendorCartel: 6, delayed: 22, total: 54 },
  { month: 'Apr 25', cost: 14, duplicateImage: 11, vendorCartel: 8, delayed: 26, total: 59 },
  { month: 'May 25', cost: 12, duplicateImage: 15, vendorCartel: 9, delayed: 31, total: 67 },
  { month: 'Jun 25', cost: 22, duplicateImage: 18, vendorCartel: 12, delayed: 24, total: 76 },
  { month: 'Jul 25', cost: 19, duplicateImage: 14, vendorCartel: 14, delayed: 29, total: 76 },
  { month: 'Aug 25', cost: 15, duplicateImage: 9, vendorCartel: 11, delayed: 18, total: 53 },
  { month: 'Sep 25', cost: 11, duplicateImage: 6, vendorCartel: 7, delayed: 15, total: 39 },
  { month: 'Oct 25', cost: 13, duplicateImage: 7, vendorCartel: 8, delayed: 14, total: 42 },
  { month: 'Nov 25', cost: 9, duplicateImage: 4, vendorCartel: 6, delayed: 12, total: 31 },
  { month: 'Dec 25', cost: 16, duplicateImage: 8, vendorCartel: 10, delayed: 16, total: 50 },
  { month: 'Jan 26', cost: 21, duplicateImage: 12, vendorCartel: 14, delayed: 20, total: 67 },
  { month: 'Feb 26', cost: 14, duplicateImage: 7, vendorCartel: 9, delayed: 15, total: 45 },
];

export const FRAUD_VS_INEFFICIENCY = [
  { name: 'Duplicate Evidence / Photo Fraud', value: 34, color: '#EF4444' },
  { name: 'Vendor Cartel & Bid Collusion', value: 28, color: '#F97316' },
  { name: 'Cost Baseline Inflation', value: 22, color: '#EAB308' },
  { name: 'SLA Milestone Delay', value: 38, color: '#3B82F6' },
  { name: 'Unutilized Idle Funds', value: 24, color: '#8B5CF6' },
];

export const CARTEL_NETWORK_DATA = {
  nodes: [
    { id: 'V-01', name: 'Apex Infra & BuildTech', type: 'vendor', risk: 89, projects: 8, districts: ['Varanasi', 'Jaunpur', 'Kamrup'] },
    { id: 'V-02', name: 'Shiva Buildcon Pvt Ltd', type: 'vendor', risk: 84, projects: 5, districts: ['Varanasi', 'Mirzapur'] },
    { id: 'V-03', name: ' पूर्वांचल Infratech', type: 'vendor', risk: 79, projects: 4, districts: ['Varanasi', 'Ghazipur'] },
    { id: 'DIR-01', name: 'R. K. Agarwal (Shared Director)', type: 'director', risk: 95, connectedVendors: 3 },
    { id: 'PRJ-124', name: 'MPLAD-00124 (Varanasi Road)', type: 'project', risk: 87 },
    { id: 'PRJ-892', name: 'MPLAD-00892 (Jaunpur Road)', type: 'project', risk: 92 },
    { id: 'PRJ-518', name: 'MPLAD-00518 (Guwahati LED)', type: 'project', risk: 74 },
    { id: 'DIST-VAR', name: 'Varanasi District Pool', type: 'district', risk: 65 },
    { id: 'DIST-JAU', name: 'Jaunpur District Pool', type: 'district', risk: 70 },
  ],
  links: [
    { source: 'DIR-01', target: 'V-01', label: 'Managing Director (40% Equity)' },
    { source: 'DIR-01', target: 'V-02', label: 'Silent Partner & Common Bank Signatory' },
    { source: 'DIR-01', target: 'V-03', label: 'Registered GST Contact Overlap' },
    { source: 'V-01', target: 'PRJ-124', label: 'L1 Bid Award (₹48L)' },
    { source: 'V-02', target: 'PRJ-124', label: 'L2 Disqualified Bidder' },
    { source: 'V-03', target: 'PRJ-124', label: 'L3 Disqualified Bidder' },
    { source: 'V-01', target: 'PRJ-892', label: 'Executed Project (2024)' },
    { source: 'V-01', target: 'PRJ-518', label: 'Current Tender Award' },
    { source: 'PRJ-124', target: 'DIST-VAR', label: 'Location' },
    { source: 'PRJ-892', target: 'DIST-JAU', label: 'Location' },
  ]
};

export const SLA_ALERTS_LIST = [
  {
    id: 'SLA-01',
    projectId: 'MPLAD-2026-00451',
    projectName: 'Solar Drinking Water RO Plant & Borewell',
    district: 'Banswara',
    deadline: '2025-12-31',
    daysRemaining: -45,
    risk: 'CRITICAL',
    status: 'Overdue (45 Days)',
    assignee: 'PHED Executive Engineer',
    actionRequired: 'Physical Commissioning Audit',
  },
  {
    id: 'SLA-02',
    projectId: 'MPLAD-2026-00231',
    projectName: 'Multi-purpose Community Hall Construction',
    district: 'North West Delhi',
    deadline: '2026-02-28',
    daysRemaining: 2,
    risk: 'CRITICAL',
    status: '2 Days Remaining',
    assignee: 'DDA Assistant Engineer',
    actionRequired: 'Stage-2 Fund Utilization Certificate',
  },
  {
    id: 'SLA-03',
    projectId: 'MPLAD-2026-00124',
    projectName: 'Rural Road Construction & Paver Block',
    district: 'Varanasi',
    deadline: '2026-03-31',
    daysRemaining: 4,
    risk: 'HIGH',
    status: '4 Days Remaining (Milestone-3)',
    assignee: 'RES Div-2 Officer',
    actionRequired: 'Photo Forensic Clearance Required',
  },
  {
    id: 'SLA-04',
    projectId: 'MPLAD-2026-00518',
    projectName: 'High-Mast LED Street Lighting',
    district: 'Kamrup Metro',
    deadline: '2026-04-30',
    daysRemaining: 8,
    risk: 'MEDIUM',
    status: '8 Days Remaining',
    assignee: 'Smart City Project Director',
    actionRequired: 'Vendor Collusion Review',
  },
  {
    id: 'SLA-05',
    projectId: 'MPLAD-2026-00089',
    projectName: 'Digital Smart Classroom Lab',
    district: 'Patna',
    deadline: '2026-01-30',
    daysRemaining: 30,
    risk: 'LOW',
    status: '30 Days Remaining',
    assignee: 'BSEIDC District Nodal',
    actionRequired: 'Final Handover Verification',
  },
];

export const CITIZEN_REPORTS_LIST = [
  {
    id: 'CIT-2026-9812',
    projectId: 'MPLAD-2026-00124',
    projectName: 'Rural Road Construction',
    issueType: 'Work Incomplete / Poor Material Quality',
    description: 'Road foundation has cracked within 2 weeks of laying. The contractor used substandard bricks and left half the lane blocked with debris.',
    location: 'Chiraigaon Block, Varanasi',
    gps: '25.3188° N, 82.9799° E',
    submissionDate: '2026-08-22',
    status: 'Under Verification',
    citizenName: 'Amit Patel',
    evidenceImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=600&auto=format&fit=crop&q=80',
    aiPreCheck: 'Geotag within 80m of project boundary. Image texture shows severe sub-base cracking.',
  },
  {
    id: 'CIT-2026-7734',
    projectId: 'MPLAD-2026-00451',
    projectName: 'Solar RO Plant Banswara',
    issueType: 'Project Does Not Exist on Ground (Ghost Asset)',
    description: 'There is only an abandoned hand pump at the marked GPS location. No solar RO plant was ever constructed.',
    location: 'Banswara Tribal Village',
    gps: '23.5450° N, 74.4360° E',
    submissionDate: '2026-08-18',
    status: 'Inspection Dispatched',
    citizenName: 'Kailash Meena',
    evidenceImage: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=600&auto=format&fit=crop&q=80',
    aiPreCheck: 'High credibility flag: 3 corroborating complaints from same village.',
  }
];

export const NOTIFICATIONS_LIST = [
  {
    id: 'NOTIF-01',
    type: 'CRITICAL',
    title: 'Critical Anomaly Detected in MPLAD-2026-00124',
    message: 'AI Vision detected 96% photo match with completed Jaunpur project MPLAD-2024-00892.',
    timestamp: '10 minutes ago',
    unread: true,
    link: '/dashboard/evidence',
  },
  {
    id: 'NOTIF-02',
    type: 'WARNING',
    title: 'SLA Milestone Approaching',
    message: 'Project MPLAD-2026-00231 in Rohini Delhi has 2 days remaining before SLA breach.',
    timestamp: '45 minutes ago',
    unread: true,
    link: '/dashboard/sla',
  },
  {
    id: 'NOTIF-03',
    type: 'INFO',
    title: 'New Citizen Grievance Logged',
    message: 'Report CIT-2026-9812 submitted with geotagged photo evidence for Varanasi Road.',
    timestamp: '2 hours ago',
    unread: false,
    link: '/dashboard/high-risk',
  },
  {
    id: 'NOTIF-04',
    type: 'SUCCESS',
    title: 'AI Verification Completed',
    message: 'Patna Smart Classroom (MPLAD-2026-00089) cleared all 5 automated integrity audits.',
    timestamp: '1 day ago',
    unread: false,
    link: '/dashboard/projects',
  },
];
