"""
MPLADS Realistic Dataset Generator
----------------------------------
Generates 65+ authentic, believable MPLADS project records covering 5 core sectors:
- Roads, Pathways and Bridges
- Drinking Water Facilities
- Education Infrastructure
- Health and Family Welfare
- Community Assets & Halls

Spanning multiple key Indian constituencies/districts:
- Varanasi, UP (Narendra Modi PC)
- Nandurbar, MH (Heena Gavit PC)
- Pune, MH (Supriya Sule PC)
- Patna, BR (Ravi Shankar Prasad PC)
- Jaipur, RJ (Ramcharan Bohara PC)
- Banswara, RJ (Kanakmal Katara PC)
- North West Delhi, DL (Dr. Harsh Vardhan PC)
- Bengaluru Urban, KA (Tejasvi Surya PC)

Includes deliberate, realistic cartel bidding patterns:
- In Varanasi: "Apex Infra & BuildTech Pvt Ltd" holds ~40% market concentration
- In Nandurbar: "Sahyadri Infra Projects LLP" holds ~38% market concentration
- Near duplicate works for text-similarity fraud detection
"""
from typing import List, Dict, Any

COMPREHENSIVE_PROJECTS_DATABASE: List[Dict[str, Any]] = [
    # --- VARANASI (Uttar Pradesh) - Focus District 1 ---
    {
        "project_id": "MPLAD-2026-00124",
        "title": "Rural Road Construction & Paver Block Laying in Rohania",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "constituency": "Shri Narendra Modi (Varanasi PC)",
        "category": "Roads, Pathways and Bridges",
        "sanctioned_amount": 4800000.0,
        "funds_released": 3200000.0,
        "funds_utilized": 2100000.0,
        "physical_progress_pct": 45.0,
        "sanction_date": "2025-08-15",
        "expected_completion_date": "2026-03-31",
        "days_elapsed": 337,
        "allocated_duration_days": 228,
        "contractor_id": "VEN-8899",
        "contractor_name": "Apex Infra & BuildTech Pvt Ltd",
        "latitude": 25.3176,
        "longitude": 82.9739,
        "evidence_image_url": "/evidence/MPLAD-2026-00124.svg",
        "image_anomaly_score": 96.0
    },
    {
        "project_id": "MPLAD-2026-00125",
        "title": "CC Road & Interlocking Drain from Shivpur to Tarna",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "constituency": "Shri Narendra Modi (Varanasi PC)",
        "category": "Roads, Pathways and Bridges",
        "sanctioned_amount": 3900000.0,
        "funds_released": 3500000.0,
        "funds_utilized": 3300000.0,
        "physical_progress_pct": 82.0,
        "sanction_date": "2025-07-10",
        "expected_completion_date": "2026-02-15",
        "days_elapsed": 240,
        "allocated_duration_days": 220,
        "contractor_id": "VEN-8899",
        "contractor_name": "Apex Infra & BuildTech Pvt Ltd",
        "latitude": 25.3524,
        "longitude": 82.9811,
        "evidence_image_url": "/evidence/MPLAD-2026-00125.svg",
        "image_anomaly_score": 12.0
    },
    {
        "project_id": "MPLAD-2026-00126",
        "title": "Solar Powered RO Drinking Water Plant at Sevapuri Block",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "constituency": "Shri Narendra Modi (Varanasi PC)",
        "category": "Drinking Water Facilities",
        "sanctioned_amount": 2800000.0,
        "funds_released": 2800000.0,
        "funds_utilized": 2750000.0,
        "physical_progress_pct": 100.0,
        "sanction_date": "2025-05-01",
        "expected_completion_date": "2025-11-30",
        "days_elapsed": 213,
        "allocated_duration_days": 213,
        "contractor_id": "VEN-4676",
        "contractor_name": "SunPower Aqua Solutions",
        "latitude": 25.2912,
        "longitude": 82.8124,
        "evidence_image_url": "/evidence/MPLAD-2026-00126.svg",
        "image_anomaly_score": 5.0
    },
    {
        "project_id": "MPLAD-2026-00127",
        "title": "Rural Road Paver Block & Interlocking in Rohania Ward 4",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "constituency": "Shri Narendra Modi (Varanasi PC)",
        "category": "Roads, Pathways and Bridges",
        "sanctioned_amount": 4200000.0,
        "funds_released": 3800000.0,
        "funds_utilized": 1800000.0,
        "physical_progress_pct": 38.0,
        "sanction_date": "2025-09-12",
        "expected_completion_date": "2026-04-30",
        "days_elapsed": 180,
        "allocated_duration_days": 230,
        "contractor_id": "VEN-8899",
        "contractor_name": "Apex Infra & BuildTech Pvt Ltd",
        "latitude": 25.3180,
        "longitude": 82.9745,
        "evidence_image_url": "/evidence/MPLAD-2026-00127.svg",
        "image_anomaly_score": 88.0
    },
    {
        "project_id": "MPLAD-2026-00128",
        "title": "High School Science & STEM Laboratory Equipment Installation",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "constituency": "Shri Narendra Modi (Varanasi PC)",
        "category": "Education Infrastructure",
        "sanctioned_amount": 2200000.0,
        "funds_released": 2200000.0,
        "funds_utilized": 2150000.0,
        "physical_progress_pct": 95.0,
        "sanction_date": "2025-06-20",
        "expected_completion_date": "2025-12-15",
        "days_elapsed": 178,
        "allocated_duration_days": 178,
        "contractor_id": "VEN-7624",
        "contractor_name": "EdTech Next India Ltd",
        "latitude": 25.3216,
        "longitude": 82.9902,
        "evidence_image_url": "/evidence/MPLAD-2026-00128.svg",
        "image_anomaly_score": 8.0
    },
    {
        "project_id": "MPLAD-2026-00129",
        "title": "Community Recreation Hall & Senior Citizen Center",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "constituency": "Shri Narendra Modi (Varanasi PC)",
        "category": "Community Assets & Halls",
        "sanctioned_amount": 3500000.0,
        "funds_released": 2500000.0,
        "funds_utilized": 2400000.0,
        "physical_progress_pct": 70.0,
        "sanction_date": "2025-08-01",
        "expected_completion_date": "2026-03-15",
        "days_elapsed": 210,
        "allocated_duration_days": 226,
        "contractor_id": "VEN-3321",
        "contractor_name": "Ganga Valley Constructions",
        "latitude": 25.2845,
        "longitude": 83.0012,
        "evidence_image_url": "/evidence/MPLAD-2026-00129.svg",
        "image_anomaly_score": 10.0
    },
    {
        "project_id": "MPLAD-2026-00130",
        "title": "District Hospital Neonatal Care Unit Oxygen Pipeline",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "constituency": "Shri Narendra Modi (Varanasi PC)",
        "category": "Health and Family Welfare",
        "sanctioned_amount": 5400000.0,
        "funds_released": 5400000.0,
        "funds_utilized": 5300000.0,
        "physical_progress_pct": 100.0,
        "sanction_date": "2025-04-10",
        "expected_completion_date": "2025-10-31",
        "days_elapsed": 204,
        "allocated_duration_days": 204,
        "contractor_id": "VEN-5540",
        "contractor_name": "MedLife Healthcare Solutions",
        "latitude": 25.3341,
        "longitude": 82.9988,
        "evidence_image_url": "/evidence/MPLAD-2026-00130.svg",
        "image_anomaly_score": 4.0
    },
    {
        "project_id": "MPLAD-2026-00131",
        "title": "Construction of Paver Road & Boundary Wall around Kashi Ghat Link",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "constituency": "Shri Narendra Modi (Varanasi PC)",
        "category": "Roads, Pathways and Bridges",
        "sanctioned_amount": 4500000.0,
        "funds_released": 4500000.0,
        "funds_utilized": 2200000.0,
        "physical_progress_pct": 40.0,
        "sanction_date": "2025-07-22",
        "expected_completion_date": "2026-01-30",
        "days_elapsed": 220,
        "allocated_duration_days": 192,
        "contractor_id": "VEN-8899",
        "contractor_name": "Apex Infra & BuildTech Pvt Ltd",
        "latitude": 25.3050,
        "longitude": 83.0105,
        "evidence_image_url": "/evidence/MPLAD-2026-00131.svg",
        "image_anomaly_score": 91.0
    },

    # --- NANDURBAR (Maharashtra) - Focus District 2 (Tribal Aspirational) ---
    {
        "project_id": "MPLAD-2026-00501",
        "title": "Tribal Hamlet Solar Water RO Filtration Plant in Dhadgaon",
        "state": "Maharashtra",
        "district": "Nandurbar",
        "constituency": "Dr. Heena Gavit (Nandurbar ST)",
        "category": "Drinking Water Facilities",
        "sanctioned_amount": 4200000.0,
        "funds_released": 3800000.0,
        "funds_utilized": 3600000.0,
        "physical_progress_pct": 90.0,
        "sanction_date": "2025-05-14",
        "expected_completion_date": "2025-12-20",
        "days_elapsed": 220,
        "allocated_duration_days": 220,
        "contractor_id": "VEN-9102",
        "contractor_name": "Sahyadri Infra Projects LLP",
        "latitude": 21.6521,
        "longitude": 74.2045,
        "evidence_image_url": "/evidence/MPLAD-2026-00501.svg",
        "image_anomaly_score": 14.0
    },
    {
        "project_id": "MPLAD-2026-00502",
        "title": "Tribal Area Road & Culvert Construction linking Molgi",
        "state": "Maharashtra",
        "district": "Nandurbar",
        "constituency": "Dr. Heena Gavit (Nandurbar ST)",
        "category": "Roads, Pathways and Bridges",
        "sanctioned_amount": 5800000.0,
        "funds_released": 5200000.0,
        "funds_utilized": 2600000.0,
        "physical_progress_pct": 42.0,
        "sanction_date": "2025-06-18",
        "expected_completion_date": "2026-02-28",
        "days_elapsed": 250,
        "allocated_duration_days": 255,
        "contractor_id": "VEN-9102",
        "contractor_name": "Sahyadri Infra Projects LLP",
        "latitude": 21.7104,
        "longitude": 74.1350,
        "evidence_image_url": "/evidence/MPLAD-2026-00502.svg",
        "image_anomaly_score": 94.0
    },
    {
        "project_id": "MPLAD-2026-00503",
        "title": "Ashram School Digital Classroom Setup & Solar Inverter",
        "state": "Maharashtra",
        "district": "Nandurbar",
        "constituency": "Dr. Heena Gavit (Nandurbar ST)",
        "category": "Education Infrastructure",
        "sanctioned_amount": 2400000.0,
        "funds_released": 2400000.0,
        "funds_utilized": 2300000.0,
        "physical_progress_pct": 98.0,
        "sanction_date": "2025-08-05",
        "expected_completion_date": "2026-01-15",
        "days_elapsed": 163,
        "allocated_duration_days": 163,
        "contractor_id": "VEN-7624",
        "contractor_name": "EdTech Next India Ltd",
        "latitude": 21.3789,
        "longitude": 74.2411,
        "evidence_image_url": "/evidence/MPLAD-2026-00503.svg",
        "image_anomaly_score": 6.0
    },
    {
        "project_id": "MPLAD-2026-00504",
        "title": "Sub-District Hospital Maternity Ward Medical Gas System",
        "state": "Maharashtra",
        "district": "Nandurbar",
        "constituency": "Dr. Heena Gavit (Nandurbar ST)",
        "category": "Health and Family Welfare",
        "sanctioned_amount": 4900000.0,
        "funds_released": 4500000.0,
        "funds_utilized": 4350000.0,
        "physical_progress_pct": 92.0,
        "sanction_date": "2025-04-20",
        "expected_completion_date": "2025-11-30",
        "days_elapsed": 224,
        "allocated_duration_days": 224,
        "contractor_id": "VEN-5540",
        "contractor_name": "MedLife Healthcare Solutions",
        "latitude": 21.3654,
        "longitude": 74.2389,
        "evidence_image_url": "/evidence/MPLAD-2026-00504.svg",
        "image_anomaly_score": 11.0
    },
    {
        "project_id": "MPLAD-2026-00505",
        "title": "Road Asphalt Overhaul & Concrete Culvert in Akkalkuwa",
        "state": "Maharashtra",
        "district": "Nandurbar",
        "constituency": "Dr. Heena Gavit (Nandurbar ST)",
        "category": "Roads, Pathways and Bridges",
        "sanctioned_amount": 6200000.0,
        "funds_released": 5800000.0,
        "funds_utilized": 2800000.0,
        "physical_progress_pct": 36.0,
        "sanction_date": "2025-07-02",
        "expected_completion_date": "2026-03-31",
        "days_elapsed": 245,
        "allocated_duration_days": 272,
        "contractor_id": "VEN-9102",
        "contractor_name": "Sahyadri Infra Projects LLP",
        "latitude": 21.5540,
        "longitude": 74.0210,
        "evidence_image_url": "/evidence/MPLAD-2026-00505.svg",
        "image_anomaly_score": 97.0
    },
    {
        "project_id": "MPLAD-2026-00506",
        "title": "Community Resource Center & Tribal Cultural Bhavan",
        "state": "Maharashtra",
        "district": "Nandurbar",
        "constituency": "Dr. Heena Gavit (Nandurbar ST)",
        "category": "Community Assets & Halls",
        "sanctioned_amount": 3800000.0,
        "funds_released": 3000000.0,
        "funds_utilized": 2900000.0,
        "physical_progress_pct": 78.0,
        "sanction_date": "2025-06-12",
        "expected_completion_date": "2026-02-15",
        "days_elapsed": 248,
        "allocated_duration_days": 248,
        "contractor_id": "VEN-2180",
        "contractor_name": "Khandesh Engineering Co",
        "latitude": 21.3701,
        "longitude": 74.2490,
        "evidence_image_url": "/evidence/MPLAD-2026-00506.svg",
        "image_anomaly_score": 9.0
    },

    # --- PUNE (Maharashtra) ---
    {
        "project_id": "MPLAD-2026-00342",
        "title": "Primary Health Centre (PHC) Medical Oxygen Pipeline in Baramati",
        "state": "Maharashtra",
        "district": "Pune",
        "constituency": "Smt. Supriya Sule (Baramati PC)",
        "category": "Health and Family Welfare",
        "sanctioned_amount": 6400000.0,
        "funds_released": 5000000.0,
        "funds_utilized": 4800000.0,
        "physical_progress_pct": 100.0,
        "sanction_date": "2025-03-15",
        "expected_completion_date": "2025-10-15",
        "days_elapsed": 214,
        "allocated_duration_days": 214,
        "contractor_id": "VEN-5540",
        "contractor_name": "MedLife Healthcare Solutions",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "evidence_image_url": "/evidence/MPLAD-2026-00342.svg",
        "image_anomaly_score": 0
    },
    {
        "project_id": "MPLAD-2026-00343",
        "title": "Rural Connect Road & Stormwater Drain in Daund",
        "state": "Maharashtra",
        "district": "Pune",
        "constituency": "Smt. Supriya Sule (Baramati PC)",
        "category": "Roads, Pathways and Bridges",
        "sanctioned_amount": 5100000.0,
        "funds_released": 4600000.0,
        "funds_utilized": 4300000.0,
        "physical_progress_pct": 85.0,
        "sanction_date": "2025-05-18",
        "expected_completion_date": "2026-01-20",
        "days_elapsed": 247,
        "allocated_duration_days": 247,
        "contractor_id": "VEN-8812",
        "contractor_name": "Deccan Civil Engineering Corp",
        "latitude": 18.4650,
        "longitude": 74.5800,
        "evidence_image_url": "/evidence/MPLAD-2026-00343.svg",
        "image_anomaly_score": 12.0
    },
    {
        "project_id": "MPLAD-2026-00344",
        "title": "Zilla Parishad High School Computer Learning Lab",
        "state": "Maharashtra",
        "district": "Pune",
        "constituency": "Smt. Supriya Sule (Baramati PC)",
        "category": "Education Infrastructure",
        "sanctioned_amount": 2500000.0,
        "funds_released": 2500000.0,
        "funds_utilized": 2480000.0,
        "physical_progress_pct": 100.0,
        "sanction_date": "2025-06-01",
        "expected_completion_date": "2025-11-30",
        "days_elapsed": 182,
        "allocated_duration_days": 182,
        "contractor_id": "VEN-7624",
        "contractor_name": "EdTech Next India Ltd",
        "latitude": 18.5300,
        "longitude": 73.8650,
        "evidence_image_url": "/evidence/MPLAD-2026-00344.svg",
        "image_anomaly_score": 4.0
    },
    {
        "project_id": "MPLAD-2026-00345",
        "title": "Community Multipurpose Hall for Women SHG Federation",
        "state": "Maharashtra",
        "district": "Pune",
        "constituency": "Smt. Supriya Sule (Baramati PC)",
        "category": "Community Assets & Halls",
        "sanctioned_amount": 3400000.0,
        "funds_released": 2900000.0,
        "funds_utilized": 2750000.0,
        "physical_progress_pct": 80.0,
        "sanction_date": "2025-07-15",
        "expected_completion_date": "2026-02-28",
        "days_elapsed": 210,
        "allocated_duration_days": 228,
        "contractor_id": "VEN-8812",
        "contractor_name": "Deccan Civil Engineering Corp",
        "latitude": 18.5120,
        "longitude": 73.8400,
        "evidence_image_url": "/evidence/MPLAD-2026-00345.svg",
        "image_anomaly_score": 15.0
    },

    # --- PATNA (Bihar) ---
    {
        "project_id": "MPLAD-2026-00089",
        "title": "Digital Smart Classroom Lab & Computer Setup at Bakhtiyarpur",
        "state": "Bihar",
        "district": "Patna",
        "constituency": "Shri Ravi Shankar Prasad (Patna Sahib)",
        "category": "Education Infrastructure",
        "sanctioned_amount": 1800000.0,
        "funds_released": 1800000.0,
        "funds_utilized": 1750000.0,
        "physical_progress_pct": 100.0,
        "sanction_date": "2025-09-01",
        "expected_completion_date": "2026-01-30",
        "days_elapsed": 151,
        "allocated_duration_days": 151,
        "contractor_id": "VEN-7624",
        "contractor_name": "EdTech Next India Ltd",
        "latitude": 25.5941,
        "longitude": 85.1376,
        "evidence_image_url": "/evidence/MPLAD-2026-00089.svg",
        "image_anomaly_score": 0
    },
    {
        "project_id": "MPLAD-2026-00090",
        "title": "Panchayat Community Library and Reading Hall in Danapur",
        "state": "Bihar",
        "district": "Patna",
        "constituency": "Shri Ravi Shankar Prasad (Patna Sahib)",
        "category": "Community Assets & Halls",
        "sanctioned_amount": 3100000.0,
        "funds_released": 2800000.0,
        "funds_utilized": 1300000.0,
        "physical_progress_pct": 32.0,
        "sanction_date": "2025-06-15",
        "expected_completion_date": "2026-02-28",
        "days_elapsed": 250,
        "allocated_duration_days": 258,
        "contractor_id": "VEN-6410",
        "contractor_name": "Magadh Infrastructure Corp",
        "latitude": 25.6295,
        "longitude": 85.0440,
        "evidence_image_url": "/evidence/MPLAD-2026-00090.svg",
        "image_anomaly_score": 85.0
    },
    {
        "project_id": "MPLAD-2026-00091",
        "title": "Solar Deep Tube Well & Clean Water Storage in Phulwari Sharif",
        "state": "Bihar",
        "district": "Patna",
        "constituency": "Shri Ravi Shankar Prasad (Patna Sahib)",
        "category": "Drinking Water Facilities",
        "sanctioned_amount": 3600000.0,
        "funds_released": 3200000.0,
        "funds_utilized": 3100000.0,
        "physical_progress_pct": 89.0,
        "sanction_date": "2025-07-20",
        "expected_completion_date": "2026-03-10",
        "days_elapsed": 220,
        "allocated_duration_days": 233,
        "contractor_id": "VEN-4676",
        "contractor_name": "SunPower Aqua Solutions",
        "latitude": 25.5780,
        "longitude": 85.0780,
        "evidence_image_url": "/evidence/MPLAD-2026-00091.svg",
        "image_anomaly_score": 16.0
    },
    {
        "project_id": "MPLAD-2026-00092",
        "title": "Bituminous Road Surfacing linking Patna City to Didarganj",
        "state": "Bihar",
        "district": "Patna",
        "constituency": "Shri Ravi Shankar Prasad (Patna Sahib)",
        "category": "Roads, Pathways and Bridges",
        "sanctioned_amount": 5500000.0,
        "funds_released": 5000000.0,
        "funds_utilized": 2400000.0,
        "physical_progress_pct": 39.0,
        "sanction_date": "2025-05-10",
        "expected_completion_date": "2026-01-31",
        "days_elapsed": 280,
        "allocated_duration_days": 266,
        "contractor_id": "VEN-6410",
        "contractor_name": "Magadh Infrastructure Corp",
        "latitude": 25.5890,
        "longitude": 85.2250,
        "evidence_image_url": "/evidence/MPLAD-2026-00092.svg",
        "image_anomaly_score": 93.0
    },

    # --- JAIPUR (Rajasthan) ---
    {
        "project_id": "MPLAD-2026-00710",
        "title": "Interlocking Tile Pathway & Solar Street Lighting in Sanganer",
        "state": "Rajasthan",
        "district": "Jaipur",
        "constituency": "Shri Ramcharan Bohara (Jaipur PC)",
        "category": "Roads, Pathways and Bridges",
        "sanctioned_amount": 4200000.0,
        "funds_released": 3800000.0,
        "funds_utilized": 3600000.0,
        "physical_progress_pct": 84.0,
        "sanction_date": "2025-06-25",
        "expected_completion_date": "2026-02-28",
        "days_elapsed": 240,
        "allocated_duration_days": 248,
        "contractor_id": "VEN-3912",
        "contractor_name": "Marwar Buildcon Services",
        "latitude": 26.8200,
        "longitude": 75.7800,
        "evidence_image_url": "/evidence/MPLAD-2026-00710.svg",
        "image_anomaly_score": 10.0
    },
    {
        "project_id": "MPLAD-2026-00711",
        "title": "Government Senior Secondary School Science Lab Modernization",
        "state": "Rajasthan",
        "district": "Jaipur",
        "constituency": "Shri Ramcharan Bohara (Jaipur PC)",
        "category": "Education Infrastructure",
        "sanctioned_amount": 2600000.0,
        "funds_released": 2600000.0,
        "funds_utilized": 2550000.0,
        "physical_progress_pct": 100.0,
        "sanction_date": "2025-05-15",
        "expected_completion_date": "2025-11-30",
        "days_elapsed": 199,
        "allocated_duration_days": 199,
        "contractor_id": "VEN-7624",
        "contractor_name": "EdTech Next India Ltd",
        "latitude": 26.9124,
        "longitude": 75.7873,
        "evidence_image_url": "/evidence/MPLAD-2026-00711.svg",
        "image_anomaly_score": 3.0
    },
    {
        "project_id": "MPLAD-2026-00712",
        "title": "Rainwater Harvesting RO Drinking Water Station in Amer",
        "state": "Rajasthan",
        "district": "Jaipur",
        "constituency": "Shri Ramcharan Bohara (Jaipur PC)",
        "category": "Drinking Water Facilities",
        "sanctioned_amount": 3400000.0,
        "funds_released": 3000000.0,
        "funds_utilized": 2900000.0,
        "physical_progress_pct": 88.0,
        "sanction_date": "2025-07-01",
        "expected_completion_date": "2026-02-15",
        "days_elapsed": 220,
        "allocated_duration_days": 229,
        "contractor_id": "VEN-4676",
        "contractor_name": "SunPower Aqua Solutions",
        "latitude": 26.9855,
        "longitude": 75.8507,
        "evidence_image_url": "/evidence/MPLAD-2026-00712.svg",
        "image_anomaly_score": 7.0
    },

    # --- BANSWARA (Rajasthan) ---
    {
        "project_id": "MPLAD-2026-00451",
        "title": "Solar Drinking Water RO Plant & Borewell at Ghatol",
        "state": "Rajasthan",
        "district": "Banswara",
        "constituency": "Shri Kanakmal Katara (Banswara ST)",
        "category": "Drinking Water Facilities",
        "sanctioned_amount": 5100000.0,
        "funds_released": 4500000.0,
        "funds_utilized": 4100000.0,
        "physical_progress_pct": 88.0,
        "sanction_date": "2025-04-12",
        "expected_completion_date": "2025-12-31",
        "days_elapsed": 471,
        "allocated_duration_days": 263,
        "contractor_id": "VEN-4676",
        "contractor_name": "SunPower Aqua Solutions",
        "latitude": 23.5461,
        "longitude": 74.4373,
        "evidence_image_url": "/evidence/MPLAD-2026-00451.svg",
        "image_anomaly_score": 98.0
    },
    {
        "project_id": "MPLAD-2026-00452",
        "title": "Tribal Connecting Bridge & Approach Road over Mahi Tributary",
        "state": "Rajasthan",
        "district": "Banswara",
        "constituency": "Shri Kanakmal Katara (Banswara ST)",
        "category": "Roads, Pathways and Bridges",
        "sanctioned_amount": 7500000.0,
        "funds_released": 6800000.0,
        "funds_utilized": 3100000.0,
        "physical_progress_pct": 34.0,
        "sanction_date": "2025-05-20",
        "expected_completion_date": "2026-03-31",
        "days_elapsed": 280,
        "allocated_duration_days": 315,
        "contractor_id": "VEN-3912",
        "contractor_name": "Marwar Buildcon Services",
        "latitude": 23.5890,
        "longitude": 74.4920,
        "evidence_image_url": "/evidence/MPLAD-2026-00452.svg",
        "image_anomaly_score": 92.0
    },

    # --- DELHI (North West Delhi) ---
    {
        "project_id": "MPLAD-2026-00231",
        "title": "Multi-purpose Community Hall Construction in Rohini Sector 16",
        "state": "Delhi",
        "district": "North West Delhi",
        "constituency": "Dr. Harsh Vardhan (Chandni Chowk)",
        "category": "Community Assets & Halls",
        "sanctioned_amount": 3200000.0,
        "funds_released": 2800000.0,
        "funds_utilized": 1400000.0,
        "physical_progress_pct": 35.0,
        "sanction_date": "2025-06-10",
        "expected_completion_date": "2026-02-28",
        "days_elapsed": 415,
        "allocated_duration_days": 263,
        "contractor_id": "VEN-4995",
        "contractor_name": "Vanguard Civilcon LLP",
        "latitude": 28.7041,
        "longitude": 77.1025,
        "evidence_image_url": "/evidence/MPLAD-2026-00231.svg",
        "image_anomaly_score": 0
    },
    {
        "project_id": "MPLAD-2026-00232",
        "title": "Public Park Solar Lighting & Senior Citizen Gazebo in Pitampura",
        "state": "Delhi",
        "district": "North West Delhi",
        "constituency": "Dr. Harsh Vardhan (Chandni Chowk)",
        "category": "Community Assets & Halls",
        "sanctioned_amount": 2100000.0,
        "funds_released": 2100000.0,
        "funds_utilized": 2050000.0,
        "physical_progress_pct": 100.0,
        "sanction_date": "2025-08-01",
        "expected_completion_date": "2025-12-31",
        "days_elapsed": 152,
        "allocated_duration_days": 152,
        "contractor_id": "VEN-4995",
        "contractor_name": "Vanguard Civilcon LLP",
        "latitude": 28.6980,
        "longitude": 77.1350,
        "evidence_image_url": "/evidence/MPLAD-2026-00232.svg",
        "image_anomaly_score": 5.0
    },

    # --- BENGALURU URBAN (Karnataka) ---
    {
        "project_id": "MPLAD-2026-00801",
        "title": "Govt PU College Digital Science Lab in Jayanagar",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "constituency": "Shri Tejasvi Surya (Bengaluru South)",
        "category": "Education Infrastructure",
        "sanctioned_amount": 2900000.0,
        "funds_released": 2900000.0,
        "funds_utilized": 2850000.0,
        "physical_progress_pct": 100.0,
        "sanction_date": "2025-06-15",
        "expected_completion_date": "2025-11-30",
        "days_elapsed": 168,
        "allocated_duration_days": 168,
        "contractor_id": "VEN-7624",
        "contractor_name": "EdTech Next India Ltd",
        "latitude": 12.9300,
        "longitude": 77.5800,
        "evidence_image_url": "/evidence/MPLAD-2026-00801.svg",
        "image_anomaly_score": 2.0
    },
    {
        "project_id": "MPLAD-2026-00802",
        "title": "Rainwater Harvesting Recharge Wells & Water ATM at Basavanagudi",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "constituency": "Shri Tejasvi Surya (Bengaluru South)",
        "category": "Drinking Water Facilities",
        "sanctioned_amount": 3700000.0,
        "funds_released": 3200000.0,
        "funds_utilized": 3100000.0,
        "physical_progress_pct": 86.0,
        "sanction_date": "2025-07-10",
        "expected_completion_date": "2026-02-28",
        "days_elapsed": 215,
        "allocated_duration_days": 233,
        "contractor_id": "VEN-4676",
        "contractor_name": "SunPower Aqua Solutions",
        "latitude": 12.9420,
        "longitude": 77.5750,
        "evidence_image_url": "/evidence/MPLAD-2026-00802.svg",
        "image_anomaly_score": 8.0
    },
]

# Expand programmatically to reach 65+ realistic projects with authentic distributions
_categories = [
    ("Roads, Pathways and Bridges", 3500000.0, 7500000.0, 180, 360),
    ("Drinking Water Facilities", 1800000.0, 4800000.0, 120, 240),
    ("Education Infrastructure", 1500000.0, 3500000.0, 90, 180),
    ("Health and Family Welfare", 3000000.0, 8000000.0, 150, 300),
    ("Community Assets & Halls", 2200000.0, 5000000.0, 180, 270)
]

_locations = [
    ("Uttar Pradesh", "Varanasi", "Shri Narendra Modi (Varanasi PC)", 25.3176, 82.9739, "VEN-8899", "Apex Infra & BuildTech Pvt Ltd"),
    ("Uttar Pradesh", "Varanasi", "Shri Narendra Modi (Varanasi PC)", 25.3250, 82.9850, "VEN-3321", "Ganga Valley Constructions"),
    ("Maharashtra", "Nandurbar", "Dr. Heena Gavit (Nandurbar ST)", 21.3789, 74.2411, "VEN-9102", "Sahyadri Infra Projects LLP"),
    ("Maharashtra", "Nandurbar", "Dr. Heena Gavit (Nandurbar ST)", 21.4120, 74.2890, "VEN-2180", "Khandesh Engineering Co"),
    ("Maharashtra", "Pune", "Smt. Supriya Sule (Baramati PC)", 18.5204, 73.8567, "VEN-8812", "Deccan Civil Engineering Corp"),
    ("Bihar", "Patna", "Shri Ravi Shankar Prasad (Patna Sahib)", 25.5941, 85.1376, "VEN-6410", "Magadh Infrastructure Corp"),
    ("Rajasthan", "Jaipur", "Shri Ramcharan Bohara (Jaipur PC)", 26.9124, 75.7873, "VEN-3912", "Marwar Buildcon Services"),
    ("Rajasthan", "Banswara", "Shri Kanakmal Katara (Banswara ST)", 23.5461, 74.4373, "VEN-4676", "SunPower Aqua Solutions"),
    ("Delhi", "North West Delhi", "Dr. Harsh Vardhan (Chandni Chowk)", 28.7041, 77.1025, "VEN-4995", "Vanguard Civilcon LLP"),
    ("Karnataka", "Bengaluru Urban", "Shri Tejasvi Surya (Bengaluru South)", 12.9300, 77.5800, "VEN-7624", "EdTech Next India Ltd")
]

counter = 1000
for i in range(42):
    cat_name, min_amt, max_amt, min_dur, max_dur = _categories[i % len(_categories)]
    st, dst, const, base_lat, base_lon, v_id, v_name = _locations[i % len(_locations)]
    
    counter += 1
    amt_factor = 0.5 + ((i * 7) % 10) / 10.0
    sanctioned = round(min_amt + (max_amt - min_amt) * amt_factor, -4)
    
    # Realistic distribution: ~20% are flagged as high financial or timeline lag
    is_lagging = (i % 5 == 0)
    if is_lagging:
        released = round(sanctioned * 0.85, -4)
        utilized = round(released * 0.40, -4)
        progress = float(round(18.0 + (i % 25), 1))
        days_el = int(max_dur * 1.25)
        alloc_dur = max_dur
        img_score = 90.0 + (i % 8)
    else:
        progress = float(round(65.0 + (i % 35), 1))
        released = round(sanctioned * (progress / 100.0) * 1.05, -4)
        released = min(sanctioned, released)
        utilized = round(released * 0.95, -4)
        days_el = int(min_dur + (max_dur - min_dur) * (progress / 100.0))
        alloc_dur = max_dur
        img_score = float(i % 15)

    proj_id = f"MPLAD-2026-{counter:05d}"
    title_prefixes = ["Construction of", "Installation of", "Upgradation of", "Civil Works for", "Provision of"]
    title = f"{title_prefixes[i % len(title_prefixes)]} {cat_name} in {dst} Block-{(i % 6) + 1}"

    COMPREHENSIVE_PROJECTS_DATABASE.append({
        "project_id": proj_id,
        "title": title,
        "state": st,
        "district": dst,
        "constituency": const,
        "category": cat_name,
        "sanctioned_amount": float(sanctioned),
        "funds_released": float(released),
        "funds_utilized": float(utilized),
        "physical_progress_pct": min(100.0, progress),
        "sanction_date": "2025-05-10",
        "expected_completion_date": "2026-03-31",
        "days_elapsed": days_el,
        "allocated_duration_days": alloc_dur,
        "contractor_id": v_id,
        "contractor_name": v_name,
        "latitude": round(base_lat + ((i % 7) - 3) * 0.012, 4),
        "longitude": round(base_lon + ((i % 5) - 2) * 0.015, 4),
        "evidence_image_url": f"/evidence/{proj_id}.svg",
        "image_anomaly_score": img_score
    })
